// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onHumidityChange();
void onTemperatureChange();
void onHumidityAlarmChange();
void onTempAlarmChange();

float humidity;
float temperature;
bool humidityAlarm;
bool tempAlarm;

void initProperties(){

    ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE, onHumidityChange);
    ArduinoCloud.addProperty(temperature, READWRITE, ON_CHANGE, onTemperatureChange);
    ArduinoCloud.addProperty(humidityAlarm, READWRITE, ON_CHANGE, onHumidityAlarmChange);
    ArduinoCloud.addProperty(tempAlarm, READWRITE, ON_CHANGE, onTempAlarmChange);


}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
